access_rules:
  repositories:
    - file://./rules.json
authenticators:
  noop:
    enabled: true
  anonymous:
    enabled: true
  jwt:
    enabled: true
    config:
      jwks_urls:
        - https://dev-kdiij5qn.auth0.com/.well-known/jwks.json
      scope_strategy: none
      required_scope:
        - open-id
      target_audience:
        - https://test.kaistack.ai
      trusted_issuers:
        - https://dev-kdiij5qn.auth0.com/
      allowed_algorithms:
        - RS256
      token_from:
        header: Authorization
        cookie: x-auth-jwt
authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
serve:
  proxy:
    port: 6660
  api:
    port: 6661
mutators:
  noop:
    enabled: true
log:
  level: debug